'''Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.'''

i1,i2,i3,sumf=1,2,0,2;
while True:
	i3=i1+i2;
	if i3>4000001:
		break
	if i3%2==0:
		sumf=sumf+i3;
	i1=i2;
	i2=i3;
print(sumf)


def Fibo(FirstNum,SecNum):
	if FirstNum<=4000000:
		if FirstNum%2==0:
			return FirstNum+Fibo(SecNum,FirstNum+SecNum)
		else:
			return Fibo(SecNum,FirstNum+SecNum)
	else:
		return 0
print(Fibo(1,2))